language: python
python:
  - "3.6"
install:
  - cp contrib/env-sample .env
  - pip install -q -r requirements.txt
script:
  - coverage run --source=sgce.core,sgce.accounts,sgce.certificates manage.py test

after_success:
  - coveralls